version: "3.8"

services:
  config-server:
    container_name: config-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - config-server-network

networks:
  config-server-network:
    driver: bridge
