spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/flaerqqqq/forum-engine-api-config-server.git
          clone-on-start: true
          repos:
            default:
              pattern: 'default'
              uri: https://github.com/flaerqqqq/forum-engine-api-config-server.git
              default-label: main
            dev:
              pattern: 'dev'
              uri: https://github.com/flaerqqqq/forum-engine-api-config-server.git
              default-label: dev
            main:
              pattern: 'prod'
              uri: https://github.com/flaerqqqq/forum-engine-api-config-server.git
              default-label: main

server:
  port: 8888

logging:
  level:
    org:
      springframework:
        cloud:
          config:
            server: DEBUG


