spring:
  profiles:
    active: git
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/flaerqqqq/forum-engine-api-configs.git
          username: flaerqqqq
          password: ${GITHUB_ACCESS_TOKEN} # used environment variables because of sensitive data
          clone-on-start: true
          refresh-rate: 15
          repos:
            default:
              pattern: 'default'
              uri: https://github.com/flaerqqqq/forum-engine-api-configs.git
              default-label: dev # temporarily for development, change to 'main' upon production stage
            dev:
              pattern: 'dev'
              uri: https://github.com/flaerqqqq/forum-engine-api-configs.git
              default-label: dev
            main:
              pattern: 'prod'
              uri: https://github.com/flaerqqqq/forum-engine-api-configs.git
              default-label: main
            test-containers:
              pattern: 'test-containers'
              uri: https://github.com/flaerqqqq/forum-engine-api-configs.git
              default-label: dev
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:test} # used environment variables because of sensitive data
      password: ${SPRING_SECURITY_USER_PASSWORD:test} # used environment variables because of sensitive data

server:
  port: 8888

logging:
  level:
    org:
      springframework:
        cloud:
          config:
            server: DEBUG


